
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import pymysql
#from Game import login_register
#from Game.login_register import id_user
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame0")

connection = pymysql.connect(
    host='localhost',
    user='root',
    password='123456',
    database='pong'
)
cursor = connection.cursor()
cursor.execute("SELECT ID_user, email, Tên_người_dùng FROM users")
rows = cursor.fetchall()
id = [row[0] for row in rows]
email = [row[1] for row in rows]
name = [row[2] for row in rows]


connection.close()
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x390")
window.configure(bg = "#2B5955")


canvas = Canvas(
    window,
    bg = "#2B5955",
    height = 390,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    350.0,
    195.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
    bg="#407777"
)
button_1.place(
    x=403.0,
    y=311.0,
    width=114.0,
    height=47.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",
    bg="#2B5955"
)
button_2.place(
    x=76.0,
    y=293.0,
    width=139.0,
    height=65.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    460.0,
    156.0,
    image=image_image_2
)

canvas.create_text(
    332.0,
    112.0,
    anchor="nw",
    text="ID:",
    fill="#EAEBED",
    font=("OpenSans Regular", 12 * -1)
)

canvas.create_text(
    332.0,
    149.0,
    anchor="nw",
    text="User name:",
    fill="#EAEBED",
    font=("OpenSans Regular", 12 * -1)
)

canvas.create_text(
    332.0,
    187.0,
    anchor="nw",
    text="Email:",
    fill="#EAEBED",
    font=("OpenSans Regular", 12 * -1)
)

canvas.create_text(
    464.0,
    112.0,
    anchor="nw",
    text=id[0],
    fill="#EAEBED",
    font=("OpenSans Regular", 12 * -1)
)

canvas.create_text(
    462.0,
    149.0,
    anchor="nw",
    text=name[0],
    fill="#EAEBED",
    font=("OpenSans Regular", 12 * -1)
)

canvas.create_text(
    467.0,
    187.0,
    anchor="nw",
    text=email[0],
    fill="#EAEBED",
    font=("OpenSans Regular", 12 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    145.0,
    156.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    146.0,
    157.0,
    image=image_image_4
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat",
    bg="#FF9388"
)
button_3.place(
    x=13.0,
    y=8.0,
    width=40.0,
    height=40.0
)
window.resizable(False, False)
window.mainloop()
